const fs = require('fs');

const vehiclesData = [
  // 1. BYD Atto 3
  {
    slug: 'byd-atto-3',
    name: 'BYD Atto 3 (Superior)',
    brand: 'BYD',
    brand_country: 'China',
    distributor: 'Mega Motor Co (Hubco)',
    powertrain: 'bev',
    body_type: 'suv',
    price_ex_factory_pkr: 8990000,
    price_formatted: 'PKR 89.90 Lakh',
    on_road_estimate_pkr: 9280000,
    battery_kwh: 49.92,
    battery_type: 'BYD Blade LFP (Cell-to-Pack)',
    wltp_range_km: 410,
    real_world_range_km: 335,
    power_hp: 201,
    power_kw: 150,
    torque_nm: 310,
    zero_to_hundred_sec: 7.3,
    top_speed_kmh: 160,
    dc_fast_charge_kw: 88,
    dc_charge_time_mins: 29,
    ac_charge_kw: 7.4,
    charging_port: 'CCS2',
    seating_capacity: 5,
    boot_space_litres: 440,
    dimensions: { length_mm: 4455, width_mm: 1875, height_mm: 1615, wheelbase_mm: 2720 },
    ground_clearance_mm: 175,
    curb_weight_kg: 1750,
    warranty: { vehicle_years: 4, vehicle_km: 100000, battery_years: 8, battery_km: 160000 },
    key_features: ['ADAS Level 2 (ICC, LKA, AEB)', 'Rotating 12.8-inch Infotainment', 'Panoramic Sunroof', 'Vehicle-to-Load (V2L) 3.3 kW', '360° View Camera'],
    hero_image_url: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=1200&auto=format&fit=crop&q=85',
  },
  // 2. BYD Seal
  {
    slug: 'byd-seal',
    name: 'BYD Seal (Performance AWD)',
    brand: 'BYD',
    brand_country: 'China',
    distributor: 'Mega Motor Co (Hubco)',
    powertrain: 'bev',
    body_type: 'sedan',
    price_ex_factory_pkr: 16990000,
    price_range_formatted: 'PKR 1.48 - 1.70 Cr',
    price_formatted: 'PKR 1.70 Cr',
    on_road_estimate_pkr: 17750000,
    battery_kwh: 82.56,
    battery_type: 'BYD Blade LFP (CTB Technology)',
    wltp_range_km: 570,
    real_world_range_km: 475,
    power_hp: 523,
    power_kw: 390,
    torque_nm: 670,
    zero_to_hundred_sec: 3.8,
    top_speed_kmh: 180,
    dc_fast_charge_kw: 150,
    dc_charge_time_mins: 26,
    ac_charge_kw: 11,
    charging_port: 'CCS2',
    seating_capacity: 5,
    boot_space_litres: 400,
    dimensions: { length_mm: 4800, width_mm: 1875, height_mm: 1460, wheelbase_mm: 2920 },
    ground_clearance_mm: 145,
    curb_weight_kg: 2150,
    warranty: { vehicle_years: 4, vehicle_km: 100000, battery_years: 8, battery_km: 160000 },
    key_features: ['Dual Motor AWD (iTAC)', '0-100 km/h in 3.8s', 'Dynaudio 12-Speaker Sound', 'Heads-Up Display (W-HUD)', 'Panoramic Silver Glass Roof'],
    hero_image_url: 'https://images.unsplash.com/photo-1617788138017-80ad40651399?w=1200&auto=format&fit=crop&q=85',
  },
  // 3. Deepal S07
  {
    slug: 'deepal-s07',
    name: 'Deepal S07 (Smart Electric SUV)',
    brand: 'Deepal',
    brand_country: 'China',
    distributor: 'Master Changan Motors',
    powertrain: 'bev',
    body_type: 'suv',
    price_ex_factory_pkr: 14999000,
    price_range_formatted: 'PKR 1.40 - 1.50 Cr',
    price_formatted: 'PKR 1.50 Cr',
    on_road_estimate_pkr: 15680000,
    battery_kwh: 66.8,
    battery_type: 'CATL Ternary Lithium (Golden Shield)',
    wltp_range_km: 485,
    real_world_range_km: 410,
    power_hp: 255,
    power_kw: 190,
    torque_nm: 320,
    zero_to_hundred_sec: 6.7,
    top_speed_kmh: 180,
    dc_fast_charge_kw: 92,
    dc_charge_time_mins: 35,
    ac_charge_kw: 7,
    charging_port: 'CCS2',
    seating_capacity: 5,
    boot_space_litres: 445,
    dimensions: { length_mm: 4750, width_mm: 1930, height_mm: 1625, wheelbase_mm: 2900 },
    ground_clearance_mm: 165,
    curb_weight_kg: 1940,
    warranty: { vehicle_years: 3, vehicle_km: 100000, battery_years: 8, battery_km: 150000 },
    key_features: ['Augmented Reality HUD (AR-HUD)', 'Frameless Doors & Electric Handles', '15.6-inch Sunflower Rotating Screen', 'Sony 14-Speaker Audio', 'Zero Gravity Front Seats'],
    hero_image_url: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=1200&auto=format&fit=crop&q=85',
  },
  // 4. Deepal L07
  {
    slug: 'deepal-l07',
    name: 'Deepal L07 (Electric Sport Sedan)',
    brand: 'Deepal',
    brand_country: 'China',
    distributor: 'Master Changan Motors',
    powertrain: 'bev',
    body_type: 'sedan',
    price_ex_factory_pkr: 13999000,
    price_formatted: 'PKR 1.40 Cr',
    on_road_estimate_pkr: 14650000,
    battery_kwh: 66.8,
    battery_type: 'CATL Ternary Lithium',
    wltp_range_km: 530,
    real_world_range_km: 445,
    power_hp: 255,
    power_kw: 190,
    torque_nm: 320,
    zero_to_hundred_sec: 5.9,
    top_speed_kmh: 170,
    dc_fast_charge_kw: 92,
    dc_charge_time_mins: 35,
    ac_charge_kw: 7,
    charging_port: 'CCS2',
    seating_capacity: 5,
    boot_space_litres: 473,
    dimensions: { length_mm: 4820, width_mm: 1890, height_mm: 1480, wheelbase_mm: 2900 },
    ground_clearance_mm: 150,
    curb_weight_kg: 1820,
    warranty: { vehicle_years: 3, vehicle_km: 100000, battery_years: 8, battery_km: 150000 },
    key_features: ['Active Electric Rear Spoiler', 'Frameless Doors', 'AR-HUD Augmented Reality', 'Qualcomm Snapdragon 8155 Cockpit', 'Intelligent Gesture Control'],
    hero_image_url: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1200&auto=format&fit=crop&q=85',
  },
  // 5. MG4 EV
  {
    slug: 'mg4-ev',
    name: 'MG4 EV (Essence & Excite)',
    brand: 'MG Pakistan',
    brand_country: 'United Kingdom / China (SAIC)',
    distributor: 'JW Auto Park (Pvt) Ltd',
    powertrain: 'bev',
    body_type: 'hatchback',
    price_ex_factory_pkr: 10990000,
    price_range_formatted: 'PKR 69.49 Lakh - 1.10 Cr',
    price_formatted: 'PKR 1.10 Cr',
    on_road_estimate_pkr: 11480000,
    battery_kwh: 64.0,
    battery_type: 'One-Pack Ultra-Thin LFP / NMC',
    wltp_range_km: 435,
    real_world_range_km: 365,
    power_hp: 201,
    power_kw: 150,
    torque_nm: 250,
    zero_to_hundred_sec: 7.7,
    top_speed_kmh: 160,
    dc_fast_charge_kw: 140,
    dc_charge_time_mins: 28,
    ac_charge_kw: 11,
    charging_port: 'CCS2',
    seating_capacity: 5,
    boot_space_litres: 363,
    dimensions: { length_mm: 4287, width_mm: 1836, height_mm: 1504, wheelbase_mm: 2705 },
    ground_clearance_mm: 150,
    curb_weight_kg: 1685,
    warranty: { vehicle_years: 5, vehicle_km: 150000, battery_years: 8, battery_km: 160000 },
    key_features: ['Rear-Wheel Drive (RWD) 50:50 Balance', 'MSP Modular Scalable Platform', '140 kW DC Hyper Charge', 'MG Pilot Driver Safety Suite', 'V2L Exterior Power Supply'],
    hero_image_url: 'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?w=1200&auto=format&fit=crop&q=85',
  },
  // 6. Honri VE 2.0 & 3.0
  {
    slug: 'honri-ve-2',
    name: 'Honri VE 2.0 & 3.0',
    brand: 'Honri',
    brand_country: 'China / Pakistan Assembler',
    distributor: 'Dewan Motors Pakistan',
    powertrain: 'bev',
    body_type: 'microcar',
    price_ex_factory_pkr: 3599000,
    price_range_formatted: 'PKR 35.99 - 43.99 Lakh',
    price_formatted: 'PKR 35.99 Lakh',
    on_road_estimate_pkr: 3720000,
    battery_kwh: 18.5,
    battery_type: 'Lithium Iron Phosphate (LFP)',
    wltp_range_km: 200,
    real_world_range_km: 165,
    power_hp: 40,
    power_kw: 30,
    torque_nm: 87,
    zero_to_hundred_sec: 14.5,
    top_speed_kmh: 100,
    dc_fast_charge_kw: 0,
    dc_charge_time_mins: 0,
    ac_charge_kw: 3.3,
    charging_port: 'GB/T',
    seating_capacity: 4,
    boot_space_litres: 130,
    dimensions: { length_mm: 3517, width_mm: 1495, height_mm: 1660, wheelbase_mm: 2495 },
    ground_clearance_mm: 130,
    curb_weight_kg: 890,
    warranty: { vehicle_years: 3, vehicle_km: 100000, battery_years: 8, battery_km: 120000 },
    key_features: ['Home 15A Socket Charging in ~7 Hours', 'Dual Airbags & ABS+EBD', '10.25-inch Touchscreen with Android Auto', 'Rear Parking Sensors & Camera', 'Ultra Low Running Cost (Rs. 3.5/km)'],
    hero_image_url: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=1200&auto=format&fit=crop&q=85',
  },
  // 7. Dongfeng Box
  {
    slug: 'dongfeng-box',
    name: 'Dongfeng Box (Nammi 01)',
    brand: 'Dongfeng',
    brand_country: 'China',
    distributor: 'GuGo Motors (Pvt) Ltd',
    powertrain: 'bev',
    body_type: 'hatchback',
    price_ex_factory_pkr: 5650000,
    price_range_formatted: 'PKR 56.50 - 66.00 Lakh',
    price_formatted: 'PKR 56.50 Lakh',
    on_road_estimate_pkr: 5850000,
    battery_kwh: 31.45,
    battery_type: 'Mach-E LFP Solid State Ready',
    wltp_range_km: 330,
    real_world_range_km: 275,
    power_hp: 94,
    power_kw: 70,
    torque_nm: 160,
    zero_to_hundred_sec: 10.6,
    top_speed_kmh: 140,
    dc_fast_charge_kw: 50,
    dc_charge_time_mins: 30,
    ac_charge_kw: 6.6,
    charging_port: 'CCS2',
    seating_capacity: 5,
    boot_space_litres: 326,
    dimensions: { length_mm: 4030, width_mm: 1810, height_mm: 1570, wheelbase_mm: 2660 },
    ground_clearance_mm: 155,
    curb_weight_kg: 1280,
    warranty: { vehicle_years: 3, vehicle_km: 100000, battery_years: 8, battery_km: 150000 },
    key_features: ['Frameless Luxury Doors', 'Hidden Flush Door Handles', '12.8-inch Floating Central Screen', '30-Minute Fast DC Charging', 'Level 2 Driving Assist'],
    hero_image_url: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=1200&auto=format&fit=crop&q=85',
  },
  // 8. Omoda E5
  {
    slug: 'omoda-e5',
    name: 'Omoda E5 (Pure Electric Crossover)',
    brand: 'Omoda',
    brand_country: 'China / Chery Automobile',
    distributor: 'Ghandhara Nissan / Chery Pakistan',
    powertrain: 'bev',
    body_type: 'crossover',
    price_ex_factory_pkr: 8990000,
    price_formatted: 'PKR 89.90 Lakh',
    on_road_estimate_pkr: 9280000,
    battery_kwh: 61.0,
    battery_type: 'LFP Blade Chemistry',
    wltp_range_km: 430,
    real_world_range_km: 360,
    power_hp: 204,
    power_kw: 150,
    torque_nm: 340,
    zero_to_hundred_sec: 7.6,
    top_speed_kmh: 172,
    dc_fast_charge_kw: 80,
    dc_charge_time_mins: 28,
    ac_charge_kw: 9.9,
    charging_port: 'CCS2',
    seating_capacity: 5,
    boot_space_litres: 380,
    dimensions: { length_mm: 4424, width_mm: 1830, height_mm: 1588, wheelbase_mm: 2630 },
    ground_clearance_mm: 165,
    curb_weight_kg: 1710,
    warranty: { vehicle_years: 5, vehicle_km: 150000, battery_years: 8, battery_km: 160000 },
    key_features: ['Sony Premium 8-Speaker Sound', '24.6-inch Curved Dual Screen', 'Level 2.5 ADAS Package (17 Features)', '540° Panoramic HD Camera', 'Vehicle-to-Load (V2L)'],
    hero_image_url: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=1200&auto=format&fit=crop&q=85',
  },
  // 9. KIA EV5
  {
    slug: 'kia-ev5',
    name: 'KIA EV5 (Air / Earth AWD)',
    brand: 'KIA',
    brand_country: 'South Korea',
    distributor: 'Lucky Motor Corporation',
    powertrain: 'bev',
    body_type: 'suv',
    price_ex_factory_pkr: 18500000,
    price_range_formatted: 'PKR 1.85 - 2.35 Cr',
    price_formatted: 'PKR 1.85 Cr',
    on_road_estimate_pkr: 19350000,
    battery_kwh: 88.1,
    battery_type: 'BYD FinDreams Blade LFP / E-GMP',
    wltp_range_km: 530,
    real_world_range_km: 440,
    power_hp: 215,
    power_kw: 160,
    torque_nm: 310,
    zero_to_hundred_sec: 8.5,
    top_speed_kmh: 185,
    dc_fast_charge_kw: 140,
    dc_charge_time_mins: 27,
    ac_charge_kw: 11,
    charging_port: 'CCS2',
    seating_capacity: 5,
    boot_space_litres: 513,
    dimensions: { length_mm: 4615, width_mm: 1875, height_mm: 1715, wheelbase_mm: 2750 },
    ground_clearance_mm: 170,
    curb_weight_kg: 2020,
    warranty: { vehicle_years: 4, vehicle_km: 100000, battery_years: 8, battery_km: 160000 },
    key_features: ['Dedicated E-GMP Global Architecture', 'Refrigerated & Heated Center Console Drawer', 'Dual 12.3-inch Panoramic Cockpit', 'Heat Pump Thermal Conditioning', 'V2L Bidirectional Discharge'],
    hero_image_url: 'https://images.unsplash.com/photo-1617788138017-80ad40651399?w=1200&auto=format&fit=crop&q=85',
  },
  // 10. Mercedes EQS SUV
  {
    slug: 'mercedes-benz-eqs-suv',
    name: 'Mercedes-Benz EQS 450+ SUV',
    brand: 'Mercedes-Benz',
    brand_country: 'Germany',
    distributor: 'Shahnawaz (Pvt) Ltd',
    powertrain: 'bev',
    body_type: 'suv',
    price_ex_factory_pkr: 34500000,
    price_range_formatted: 'PKR 3.0 Cr+',
    price_formatted: 'PKR 3.45 Cr',
    on_road_estimate_pkr: 36200000,
    battery_kwh: 118.0,
    battery_type: 'NCM Matrix Lithium-Ion (EVA Platform)',
    wltp_range_km: 600,
    real_world_range_km: 510,
    power_hp: 355,
    power_kw: 265,
    torque_nm: 800,
    zero_to_hundred_sec: 4.4,
    top_speed_kmh: 210,
    dc_fast_charge_kw: 200,
    dc_charge_time_mins: 31,
    ac_charge_kw: 22,
    charging_port: 'CCS2',
    seating_capacity: 7,
    boot_space_litres: 645,
    dimensions: { length_mm: 5125, width_mm: 1959, height_mm: 1718, wheelbase_mm: 3210 },
    ground_clearance_mm: 180,
    curb_weight_kg: 2810,
    warranty: { vehicle_years: 3, vehicle_km: 100000, battery_years: 10, battery_km: 250000 },
    key_features: ['56-inch Curved MBUX Hyperscreen', 'AIRMATIC Air Suspension with Adaptive ADS+', '10° Rear-Axle Steering System', 'Burmester 3D Surround Sound with Dolby Atmos', 'HEPA Filtration Clean Air Filter'],
    hero_image_url: 'https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=1200&auto=format&fit=crop&q=85',
  },
  // 11. Audi Q8 e-tron
  {
    slug: 'audi-q8-55-etron',
    name: 'Audi Q8 55 e-tron quattro',
    brand: 'Audi',
    brand_country: 'Germany',
    distributor: 'Audi Pakistan / Premier Systems',
    powertrain: 'bev',
    body_type: 'suv',
    price_ex_factory_pkr: 48000000,
    price_range_formatted: 'PKR 4.80 Cr+',
    price_formatted: 'PKR 4.80 Cr',
    on_road_estimate_pkr: 50400000,
    battery_kwh: 114.0,
    battery_type: 'Liquid-Cooled NMC Prism Cells',
    wltp_range_km: 582,
    real_world_range_km: 490,
    power_hp: 402,
    power_kw: 300,
    torque_nm: 664,
    zero_to_hundred_sec: 5.6,
    top_speed_kmh: 200,
    dc_fast_charge_kw: 170,
    dc_charge_time_mins: 31,
    ac_charge_kw: 22,
    charging_port: 'CCS2',
    seating_capacity: 5,
    boot_space_litres: 569,
    dimensions: { length_mm: 4915, width_mm: 1937, height_mm: 1633, wheelbase_mm: 2928 },
    ground_clearance_mm: 176,
    curb_weight_kg: 2585,
    warranty: { vehicle_years: 3, vehicle_km: 100000, battery_years: 8, battery_km: 160000 },
    key_features: ['Electric quattro All-Wheel Drive', 'Adaptive Air Suspension', 'Bang & Olufsen 3D Premium Sound', 'Virtual Exterior Camera Mirrors', 'Matrix LED Headlamps'],
    hero_image_url: 'https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?w=1200&auto=format&fit=crop&q=85',
  },
  // 12. JMEV EV3
  {
    slug: 'jmev-ev3',
    name: 'JMEV EV3 (Youth Edition)',
    brand: 'JMEV',
    brand_country: 'China / France',
    distributor: 'Private Importers & Assemblies',
    powertrain: 'bev',
    body_type: 'microcar',
    price_ex_factory_pkr: 4900000,
    price_formatted: 'PKR 49.00 Lakh',
    on_road_estimate_pkr: 5080000,
    battery_kwh: 31.1,
    battery_type: 'LFP Pack',
    wltp_range_km: 270,
    real_world_range_km: 225,
    power_hp: 48,
    power_kw: 36,
    torque_nm: 150,
    zero_to_hundred_sec: 12.0,
    top_speed_kmh: 110,
    dc_fast_charge_kw: 30,
    dc_charge_time_mins: 40,
    ac_charge_kw: 3.3,
    charging_port: 'GB/T',
    seating_capacity: 4,
    boot_space_litres: 150,
    dimensions: { length_mm: 3720, width_mm: 1640, height_mm: 1535, wheelbase_mm: 2390 },
    ground_clearance_mm: 140,
    curb_weight_kg: 1020,
    warranty: { vehicle_years: 3, vehicle_km: 80000, battery_years: 8, battery_km: 120000 },
    key_features: ['Compact 5-Door Urban Layout', 'Touchscreen with Bluetooth Audio', 'Fast DC Charging Port', 'Rear View Camera', 'Air Conditioning & Power Windows'],
    hero_image_url: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1200&auto=format&fit=crop&q=85',
  },
  // 13. Chery Tiggo 7 Pro PHEV
  {
    slug: 'chery-tiggo-7-pro-phev',
    name: 'Chery Tiggo 7 Pro PHEV',
    brand: 'Chery',
    brand_country: 'China',
    distributor: 'Ghandhara Nissan Pakistan',
    powertrain: 'phev',
    body_type: 'suv',
    price_ex_factory_pkr: 9999000,
    price_formatted: 'PKR 99.99 Lakh',
    on_road_estimate_pkr: 10450000,
    battery_kwh: 18.3,
    battery_type: 'Gotion LFP High-Density',
    electric_range_km: 90,
    combined_range_km: 1200,
    wltp_range_km: 1200,
    power_hp: 342,
    power_kw: 255,
    torque_nm: 525,
    engine: '1.5L Turbocharged Petrol + Dual Electric Motors',
    transmission: '3-Speed Dedicated Hybrid Transmission (DHT)',
    zero_to_hundred_sec: 7.0,
    top_speed_kmh: 180,
    dc_fast_charge_kw: 40,
    dc_charge_time_mins: 25,
    ac_charge_kw: 6.6,
    charging_port: 'CCS2',
    seating_capacity: 5,
    boot_space_litres: 475,
    dimensions: { length_mm: 4500, width_mm: 1842, height_mm: 1705, wheelbase_mm: 2670 },
    ground_clearance_mm: 180,
    curb_weight_kg: 1790,
    warranty: { vehicle_years: 5, vehicle_km: 150000, battery_years: 8, battery_km: 160000 },
    key_features: ['Dual Motor 3-Speed DHT Hybrid Architecture', '1,200 km Intercity Combined Range', '40 kW DC Fast Charge Support', 'Sony 8-Speaker Premium Sound', 'Level 2 ADAS Safety Suite'],
    hero_image_url: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=1200&auto=format&fit=crop&q=85',
  },
  // 14. MG HS PHEV
  {
    slug: 'mg-hs-phev',
    name: 'MG HS PHEV',
    brand: 'MG Pakistan',
    brand_country: 'United Kingdom / China (SAIC)',
    distributor: 'JW Auto Park (Pvt) Ltd',
    powertrain: 'phev',
    body_type: 'suv',
    price_ex_factory_pkr: 10200000,
    price_formatted: 'PKR 1.02 Cr',
    on_road_estimate_pkr: 10680000,
    battery_kwh: 16.6,
    battery_type: 'CATL Lithium-Ion',
    electric_range_km: 135,
    combined_range_km: 1050,
    wltp_range_km: 1050,
    power_hp: 258,
    power_kw: 190,
    torque_nm: 370,
    engine: '1.5L Turbo GDI Petrol Engine',
    zero_to_hundred_sec: 6.9,
    top_speed_kmh: 190,
    dc_fast_charge_kw: 0,
    dc_charge_time_mins: 0,
    ac_charge_kw: 7.0,
    charging_port: 'Type 2',
    seating_capacity: 5,
    boot_space_litres: 463,
    dimensions: { length_mm: 4574, width_mm: 1876, height_mm: 1685, wheelbase_mm: 2720 },
    ground_clearance_mm: 175,
    curb_weight_kg: 1775,
    warranty: { vehicle_years: 5, vehicle_km: 150000, battery_years: 8, battery_km: 160000 },
    key_features: ['10-Speed Edu Hybrid Transmission', '135 km Pure EV City Commute', 'Bader Leather Bucket Sport Seats', 'MG Trophy Red Styling Accents', '10.1-inch Color Touchscreen'],
    hero_image_url: 'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?w=1200&auto=format&fit=crop&q=85',
  },
  // 15. Forthing Friday REEV
  {
    slug: 'forthing-friday-reev',
    name: 'Forthing Friday REEV',
    brand: 'Forthing',
    brand_country: 'China',
    distributor: 'Dongfeng Liuzhou Motors (Private Network)',
    powertrain: 'reev',
    body_type: 'suv',
    price_ex_factory_pkr: 9999000,
    price_formatted: 'PKR 99.99 Lakh',
    on_road_estimate_pkr: 10450000,
    battery_kwh: 31.2,
    battery_type: 'CATL Armor Liquid Cooled Battery',
    electric_range_km: 220,
    combined_range_km: 1150,
    wltp_range_km: 1150,
    power_hp: 201,
    power_kw: 150,
    torque_nm: 310,
    engine: '1.5L High Efficiency Range Extender Generator',
    zero_to_hundred_sec: 7.9,
    top_speed_kmh: 180,
    dc_fast_charge_kw: 60,
    dc_charge_time_mins: 32,
    ac_charge_kw: 6.6,
    charging_port: 'CCS2',
    seating_capacity: 5,
    boot_space_litres: 480,
    dimensions: { length_mm: 4600, width_mm: 1860, height_mm: 1680, wheelbase_mm: 2715 },
    ground_clearance_mm: 175,
    curb_weight_kg: 1820,
    warranty: { vehicle_years: 5, vehicle_km: 150000, battery_years: 8, battery_km: 160000 },
    key_features: ['220 km Pure Electric City Cruising', 'Range-Extender Engine Generator (Never Stalled)', '1,150 km Combined Intercity Range', 'Ventilated & Heated Leather Seats', 'Panoramic Starlight Sunroof'],
    hero_image_url: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=1200&auto=format&fit=crop&q=85',
  },
  // 16. Jaecoo J7 SHS
  {
    slug: 'jaecoo-j7-shs',
    name: 'Jaecoo J7 SHS (Super Hybrid)',
    brand: 'Jaecoo',
    brand_country: 'China',
    distributor: 'Chery Automobile Pakistan',
    powertrain: 'phev',
    body_type: 'suv',
    price_ex_factory_pkr: 10500000,
    price_formatted: 'PKR 1.05 Cr',
    on_road_estimate_pkr: 10980000,
    battery_kwh: 33.67,
    battery_type: 'CATL LFP Extended Pack',
    electric_range_km: 190,
    combined_range_km: 1250,
    wltp_range_km: 1250,
    power_hp: 342,
    power_kw: 255,
    torque_nm: 525,
    engine: '1.5L TGDI dedicated fifth-gen hybrid engine',
    zero_to_hundred_sec: 7.2,
    top_speed_kmh: 185,
    dc_fast_charge_kw: 45,
    dc_charge_time_mins: 28,
    ac_charge_kw: 6.6,
    charging_port: 'CCS2',
    seating_capacity: 5,
    boot_space_litres: 412,
    dimensions: { length_mm: 4500, width_mm: 1865, height_mm: 1680, wheelbase_mm: 2672 },
    ground_clearance_mm: 200,
    curb_weight_kg: 1880,
    warranty: { vehicle_years: 5, vehicle_km: 150000, battery_years: 8, battery_km: 160000 },
    key_features: ['ARDIS Off-Road All-Terrain Drive System', '200 mm High Ground Clearance for PK Terrain', '14.8-inch Vertical Studio Console', 'Sony Sound System & Double Glazing', 'V2L 3.3 kW Outdoor Camping Electricity'],
    hero_image_url: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1200&auto=format&fit=crop&q=85',
  },
  // 17. Changan Nevo Hunter REEV
  {
    slug: 'changan-nevo-hunter-reev',
    name: 'Changan Nevo Hunter 4WD REEV',
    brand: 'Deepal',
    brand_country: 'China',
    distributor: 'Master Changan Motors',
    powertrain: 'reev',
    body_type: 'pickup',
    price_ex_factory_pkr: 11000000,
    price_formatted: 'PKR 1.10 Cr',
    on_road_estimate_pkr: 11500000,
    battery_kwh: 31.18,
    battery_type: 'Changan Golden Shield LFP',
    electric_range_km: 131,
    combined_range_km: 1031,
    wltp_range_km: 1031,
    power_hp: 268,
    power_kw: 200,
    torque_nm: 470,
    engine: '2.0T Blue Core Range Extender Engine',
    zero_to_hundred_sec: 7.9,
    top_speed_kmh: 160,
    dc_fast_charge_kw: 50,
    dc_charge_time_mins: 30,
    ac_charge_kw: 6.6,
    charging_port: 'CCS2',
    seating_capacity: 5,
    boot_space_litres: 1100,
    dimensions: { length_mm: 5380, width_mm: 1930, height_mm: 1885, wheelbase_mm: 3180 },
    ground_clearance_mm: 220,
    curb_weight_kg: 2250,
    warranty: { vehicle_years: 3, vehicle_km: 100000, battery_years: 8, battery_km: 150000 },
    key_features: ['Dual-Motor 4x4 Off-Road Electric Architecture', '220 mm Rugged Ground Clearance', '3.3 kW Multi-Socket Cargo Bed Power Supply', '1 Ton Payload & Heavy Duty Towing', '1,031 km Long Distance Highway Range'],
    hero_image_url: 'https://images.unsplash.com/photo-1617788138017-80ad40651399?w=1200&auto=format&fit=crop&q=85',
  },
  // 18. GWM Haval H6 HEV & Tank 500 HEV
  {
    slug: 'gwm-haval-h6-hev',
    name: 'GWM Haval H6 HEV (Hybrid)',
    brand: 'GWM',
    brand_country: 'China',
    distributor: 'Sazgar Engineering Works Ltd',
    powertrain: 'hev',
    body_type: 'suv',
    price_ex_factory_pkr: 11700000,
    price_range_formatted: 'PKR 1.17 Cr / Tank 500 PKR 2.05 Cr',
    price_formatted: 'PKR 1.17 Cr',
    on_road_estimate_pkr: 12250000,
    battery_kwh: 1.8,
    battery_type: 'Direct Self-Charging Ternary Lithium',
    wltp_range_km: 1000,
    power_hp: 240,
    power_kw: 179,
    torque_nm: 530,
    engine: '1.5L Turbo Petrol + 2-Speed DHT Electric Motor',
    zero_to_hundred_sec: 7.5,
    top_speed_kmh: 180,
    dc_fast_charge_kw: 0,
    dc_charge_time_mins: 0,
    ac_charge_kw: 0,
    charging_port: 'Self-Charging (No Plug Needed)',
    seating_capacity: 5,
    boot_space_litres: 600,
    dimensions: { length_mm: 4683, width_mm: 1886, height_mm: 1730, wheelbase_mm: 2738 },
    ground_clearance_mm: 175,
    curb_weight_kg: 1720,
    warranty: { vehicle_years: 5, vehicle_km: 150000, battery_years: 8, battery_km: 160000 },
    key_features: ['No External Plug or Charging Required (Self-Charging)', '18-20 km/L Real Pakistani City Mileage', 'Full Level 2 Autonomous Emergency Braking', 'Heads-Up Display & Wireless Smartphone Charging', 'Panoramic Dual Sunroof'],
    hero_image_url: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=1200&auto=format&fit=crop&q=85',
  }
];

// Write to public/data/vehicles.json
fs.writeFileSync('public/data/vehicles.json', JSON.stringify(vehiclesData, null, 2), 'utf8');

// Write to data/vehicles.json
if (!fs.existsSync('data')) {
  fs.mkdirSync('data', { recursive: true });
}
fs.writeFileSync('data/vehicles.json', JSON.stringify(vehiclesData, null, 2), 'utf8');

console.log(`Successfully generated vehicles.json with ${vehiclesData.length} verified vehicles in public/data/ and data/`);
